# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ingestion_pb2 as ingestion__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ingestion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseDocument = channel.unary_unary(
                '/keiko.ingestion.v1.IngestionService/ParseDocument',
                request_serializer=ingestion__pb2.ParseDocumentRequest.SerializeToString,
                response_deserializer=ingestion__pb2.ParseDocumentResponse.FromString,
                _registered_method=True)
        self.ParseDocumentStream = channel.unary_stream(
                '/keiko.ingestion.v1.IngestionService/ParseDocumentStream',
                request_serializer=ingestion__pb2.ParseDocumentRequest.SerializeToString,
                response_deserializer=ingestion__pb2.Chunk.FromString,
                _registered_method=True)
        self.GetSupportedFormats = channel.unary_unary(
                '/keiko.ingestion.v1.IngestionService/GetSupportedFormats',
                request_serializer=ingestion__pb2.GetSupportedFormatsRequest.SerializeToString,
                response_deserializer=ingestion__pb2.GetSupportedFormatsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/keiko.ingestion.v1.IngestionService/HealthCheck',
                request_serializer=ingestion__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ingestion__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class IngestionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ParseDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseDocumentStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportedFormats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseDocument,
                    request_deserializer=ingestion__pb2.ParseDocumentRequest.FromString,
                    response_serializer=ingestion__pb2.ParseDocumentResponse.SerializeToString,
            ),
            'ParseDocumentStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ParseDocumentStream,
                    request_deserializer=ingestion__pb2.ParseDocumentRequest.FromString,
                    response_serializer=ingestion__pb2.Chunk.SerializeToString,
            ),
            'GetSupportedFormats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedFormats,
                    request_deserializer=ingestion__pb2.GetSupportedFormatsRequest.FromString,
                    response_serializer=ingestion__pb2.GetSupportedFormatsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ingestion__pb2.HealthCheckRequest.FromString,
                    response_serializer=ingestion__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'keiko.ingestion.v1.IngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('keiko.ingestion.v1.IngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ParseDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keiko.ingestion.v1.IngestionService/ParseDocument',
            ingestion__pb2.ParseDocumentRequest.SerializeToString,
            ingestion__pb2.ParseDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseDocumentStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/keiko.ingestion.v1.IngestionService/ParseDocumentStream',
            ingestion__pb2.ParseDocumentRequest.SerializeToString,
            ingestion__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportedFormats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keiko.ingestion.v1.IngestionService/GetSupportedFormats',
            ingestion__pb2.GetSupportedFormatsRequest.SerializeToString,
            ingestion__pb2.GetSupportedFormatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keiko.ingestion.v1.IngestionService/HealthCheck',
            ingestion__pb2.HealthCheckRequest.SerializeToString,
            ingestion__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
